name: Release Drawing Tool
on:
  workflow_dispatch:
    inputs:
      version:
        description: The git tag for the version of 'drawing-tool.js' to use
        required: true

env:
  BUCKET: models-resources
  PREFIX: ${{ github.event.repository.name }}
  SRC_FILE: drawing-tool.js
  DEST_FILE: drawing-tool.js
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: >
          aws s3 cp
          s3://${{ env.BUCKET }}/${{ env.PREFIX }}/version/${{ github.event.inputs.version }}/${{ env.SRC_FILE }}
          s3://${{ env.BUCKET }}/${{ env.PREFIX }}/${{ env.DEST_FILE }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.V3_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.V3_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
