name: Release Drawing Tool
on:
  workflow_dispatch:
    inputs:
      version:
        description: The git tag to release
        required: true

env:
  BUCKET: models-resources
  PREFIX: ${{ github.event.repository.name }}
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: >
          aws s3 cp --recursive
            s3://${{ env.BUCKET }}/${{ env.PREFIX }}/version/${{ github.event.inputs.version }}/
            s3://${{ env.BUCKET }}/${{ env.PREFIX }}/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.V3_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.V3_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
